version: "3.9"
services:
  web:
    build: ./frontend
    command: yarn start
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    command: yarn start
    ports:
      - "3030:3030"
    environment:
      PORT: 3030
      DB_URI: mongodb://mongodb:27017/masterwork
      JWT_SECRET: 8306101433w4t5wdfvyafadAAE
    depends_on: 
      - frontend
  mongodb:
    image: mongo:5.0
    restart: always
    ports: 
    - "27000:27017"
