paths:
  /api/cart:
    get:
      summary: 'Get all orders with pending status'
      tags:
        - api
      responses:
        200:
          description: 'Object which contains array of pending orders'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartSchema'
        500:
          description: 'Response error object'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Unknown error happened'
    delete:
      summary: 'Delete all pending orders'
      security:
        - bearerAuth: []
      tags:
        - api
      responses:
        200:
          description: 'Response: the number of deleted items'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 3

        401:
          description: 'Unauthorized error object'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorizedSchema'
  /api/cart/{orderId}:
    patch:
      summary: 'Update quantity of product'
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
            required: true
            description: Object id of the order to update.
      security:
        - bearerAuth: []
      tags:
        - api
      responses:
        200:
          description: 'If quantity became 0, deletes product from cart and give back the deleted item data. If not 0, gives the modified item with the new quantity'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    example: # Sample object
                      image: pot1_mws3pt.jpg
                      name: Rozsdamentes fazék 11cm
                      orderDate: 2022-06-19T14:48:45.348Z
                      price: 6000
                      productId: 628a63d71c406603c88d2244
                      qty: 2
                      status: pending
                      userId: 62ae1f1e346471819ae53ff5
                      __v: 0
                      _id: 62af374d6185ff4762722067

        401:
          description: 'Unauthorized error object'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorizedSchema'

components:
  schemas:
    unauthorizedSchema:
      type: object
      properties:
        message:
          type: string
          example: 'Missing token.'
    cartSchema:
      type: object
      properties:
        cartItems:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                example: 627a7fe49ccdcf2f608bf944
              name:
                type: string
                example: Product1
              price:
                type: number
                example: 2000
              quantity:
                type: number
                example: 24
              status:
                type: string
                example: pending
              image:
                type: string
                example: 'serpenyo.jpg'
              orderDate:
                type: date-time
                example: 2022-05-05T12:48:32.584+00:00
              userId:
                type: string
                example: 627a7fe49ccdcf2f608bf944
              productId:
                type: string
                example: 627a7fe49ccdcf2f608bf944
